# FILES

$files = Get-ChildItem -Path $PSScriptRoot/functions/*.ps1 -Exclude *.Tests.ps1 -Recurse | Sort-Object -Property FullName
$files | Format-Table FullName

# PSM1

$script = 
@"
# ---------
# DO NOT EDIT THIS FILE. This file is auto-generated by Build.ps1.
# ---------

$($files | ForEach-Object { (Get-Content $_.FullName | Out-String).Trim() }| Join-String -Separator "`n`n")
"@ 

Set-Content -Value $script -Path $PSScriptRoot/module/Spotify.psm1

# PS1XML

$formats = 
@"
<?xml version="1.0" encoding="utf-8" ?>
<Configuration>
  <ViewDefinitions>
  $(Get-ChildItem $PSScriptRoot/formats/*.ps1xml | ForEach-Object { ([xml](Get-Content $_)).Configuration.ViewDefinitions.View.OuterXml })
  </ViewDefinitions>
</Configuration>
"@

([xml]$formats).Save("$PSScriptRoot/module/Spotify.Formats.ps1xml");

# PSD1

$m = Test-ModuleManifest $PSScriptRoot/module/Spotify.psd1
Update-ModuleManifest `
    -Path $PSScriptRoot/module/Spotify.psd1 `
    -FunctionsToExport ($files | ForEach-Object { $_.BaseName }) `
    -ModuleVersion "$($m.Version.Major).$($m.Version.Minor).$($m.Version.Build + 1)" 
